In [1]:
import pandas as pd

## Q1. Pandas version

What version of Pandas did you install?

In [2]:
pd.__version__

'3.0.6'

## Q2. Records count

### Getting the data 

For this homework, we'll use the 2026 Car Fuel Efficiency dataset. Download it from <a href='https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv'>here</a>.

You can do it with wget:

In [3]:
#!wget -P ../data https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

How many records are in the dataset?

In [4]:
df = pd.read_csv('../data/car_fuel_efficiency_2026.csv')
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
df.shape[0] # count the rows

10000

## Q3. Fuel types

How many fuel types are presented in the dataset?

In [6]:
df['fuel_type'].describe()

count        10000
unique           3
top       Gasoline
freq          6913
Name: fuel_type, dtype: object

In [7]:
df['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

## Q4. Missing values

How many columns in the dataset have missing values?

In [8]:
cols_with_bool_true = df.isnull().sum() > 0
cols_with_bool_true

model_year             False
origin                 False
fuel_type              False
drivetrain             False
num_doors              False
engine_displacement    False
num_cylinders          False
horsepower              True
vehicle_weight         False
acceleration            True
fuel_efficiency_mpg    False
dtype: bool

In [9]:
cols_with_bool_true.sum()

np.int64(2)

# Q5. Max fuel efficiency

What's the maximum fuel efficiency of cars from Asia?

In [10]:
df[
    (df['origin'] == 'Asia') & (df['fuel_efficiency_mpg'])
].max()

model_year                         2024
origin                             Asia
fuel_type                        Hybrid
drivetrain             Rear-wheel drive
num_doors                             5
engine_displacement                3020
num_cylinders                         8
horsepower                        334.0
vehicle_weight                     5280
acceleration                       23.8
fuel_efficiency_mpg                41.2
dtype: object

# Q6. Median value of horsepower

1. Find the median value of the `horsepower` column in the dataset.

In [11]:
df.horsepower.describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [12]:
df.horsepower.median()

np.float64(254.0)

2. Next, calculate the most frequent value of the same `horsepower` column.

In [13]:
df.horsepower.mode() # ´the most frequent value´

0    252.0
Name: horsepower, dtype: float64

In [14]:
horsepower_mode = df.horsepower.mode()[0]
df.horsepower.mode()

0    252.0
Name: horsepower, dtype: float64

In [15]:
df['horsepower'].mode().iloc[0]

np.float64(252.0)

3. Use the `fillna` method to fill the missing values in the `horsepower` column with the most frequent value from the previous step.

In [16]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [17]:
df['horsepower'].isna().sum()

np.int64(877)

In [18]:
df = df.fillna({'horsepower':horsepower_mode})
df

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
...,...,...,...,...,...,...,...,...,...,...,...
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [19]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower               0
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [20]:
df.horsepower.describe()

count    10000.000000
mean       254.231500
std         21.830757
min        171.000000
25%        241.000000
50%        252.000000
75%        268.000000
max        334.000000
Name: horsepower, dtype: float64

4. Now, calculate the median value of `horsepower` once again.

In [21]:
df.horsepower.median()

np.float64(252.0)

Has it changed?

> Yes, it decreased

## Q7. Sum of weights

1. Select all the cars from Asia
2. Select only columns `vehicle_weight` and `model_year`
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it `X`.
5. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
6. Invert `XTX`.
7. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100, 1200]`.
8. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
9. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [22]:
import numpy as np

In [23]:
# 1 & 2 & 3. Filter Asia, select columns, first 7 rows
X = (
    df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']]
    .head(7)
    .values  # 4. Get numpy array
)
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [24]:
XT = X.T # transpose
XT

array([[4240, 4310, 4230, 4420, 3950, 4750, 4450],
       [1996, 1992, 1997, 1978, 2007, 2021, 2019]])

In [25]:
XTX = XT @ X # matrix - matrix Multiplication w/@
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [26]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [27]:
XTX_inv = np.linalg.inv(XTX) # Inverse
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [28]:
w = (XTX_inv @ XT) @ y 
w

array([0.13644777, 0.2327492 ])

In [29]:
w.sum()

np.float64(0.36919696904925203)